config/routes.rb
Rails.application.routes.draw do
  
  get '/tutorials', :controller => 'static_pages', :action => 'show', :id => 1
  get '/about', :controller => 'static_pages', :action => 'show', :id => 2
  get '/contacts', :controller => 'static_pages', :action => 'show', :id => 3
  resources :static_pages, :only => [:show, :edit, :update]

  devise_for :users, :path_names => { :sign_up => "register",
    :sign_in => "signin",
    :sign_out => "signout" }
    mount Ckeditor::Engine => '/ckeditor'

    root to: "articles#index"
    resources :articles
  end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role.name == "Admin"
      can :manage, :all
    else
      can :read, Article
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :title, :body
  validates_uniqueness_of :title

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base

  validates_presence_of :title, :body
  validates_uniqueness_of :title

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :articles
  belongs_to :role


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  before_filter do
  	resource = controller_name.singularize.to_sym
  	method = "#{resource}_params"
  	params[resource] &&= send(method) if respond_to?(method, true)
  end

  protected

def configure_permitted_parameters
	devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:username, :email, :password, :password_confirmation) }
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]



  def index
    if user_signed_in?
      if current_user.role.name == "Admin"
        @articles = Article.all.order('created_at DESC')
      else
        @articles = Article.all.where(:published => true).order('created_at DESC')
      end
    else
      @articles = Article.all.where(:published => true).order('created_at DESC')
    end
  end


  def show
  end


  def new
    @article = Article.new
    @article.user = current_user
  end


  def edit
  end


  require "html_truncator"
  def create
    @article = Article.new(article_params)
    @article.preview = HTML_Truncator.truncate(@article.body, 300)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @article.preview = HTML_Truncator.truncate(article_params[:body], 300)

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :body, :published)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update]

  # GET /static_pages
  # GET /static_pages.json
  def index
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params.require(:static_page).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<% content_for :head do %>
<%= javascript_include_tag "/assets/ckeditor/ckeditor" %>
<%= javascript_include_tag "/assets/ckeditor/init" %>
<% end %>

<%= form_for(@static_page) do |f| %>
<% if @static_page.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

	<ul>
		<% @static_page.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field form-group">
	<%= f.text_area :body, :class => 'ckeditor' %>
</div>

<div class="actions">
	<%= f.submit :class => 'btn btn-primary' %>
	<%= link_to 'Back', :root, :class => "btn btn-default" %>
</div>

<% end %>

app/views/articles/edit.html.erb
<% content_for :head do %>
	<title>CoC Blog - Edit Article "<%= @article.title %>"</title>
<% end %>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<%= render 'form' %>
	</div>
</div>

app/views/articles/index.html.erb
<% content_for :head do %>
	<title>CoC Blog - All Articles</title>
<% end %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

      <% if can? :create, @article %>
      <%= link_to 'New Article', new_article_path, :class => 'btn btn-primary' %><br />
      <% end %>

      <% @articles.each do |article| %>

      <div class="page-header">
        <h1><%= link_to article.title, article %></h1>
      </div>

      <p>
        <em>
          Posted by <%= article.user %> on <%= article.created_at.strftime("%B %d, %Y") %><br />
          last update <%= article.updated_at.strftime("%B %d, %Y") %><br />
        </em>
      </p>

      <div class="btn-group btn-group-lg" role="group" aria-label="Small button group">
        <%= link_to 'Read', article, :class => "btn btn-read" %>

        <% if can? :update, article %>
        <%= link_to 'Edit', edit_article_path(article), :class => "btn btn-edit" %>
        <% end %>

        <% if can? :destroy, article %>
        <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-delete" %>
        <% end %>
      </div>

      <% end %><!-- @articles.each do |article| -->
  </div>
</div>

app/views/articles/new.html.erb
<% content_for :head do %>
	<title>CoC Blog - New Article</title>
<% end %>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<h1>New article</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/articles/show.html.erb
<% content_for :head do %>
	<title>CoC Blog - <%= @article.title %></title>
<% end %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

      <div class="page-header">
        <h1><%= @article.title %></h1>
      </div>

      <div class="content">
        <%= @article.body.html_safe %>
      </div>

      <div class="buttons">
        <% if can? :update, @article %>
        <%= link_to 'Edit', edit_article_path(@article), :class => "btn btn-edit" %>
        <% end %>

        <% if can? :destroy, @article %>
        <%= link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-delete" %>
        <% end %>

        <%= link_to 'Back', articles_path, :class => "btn btn-default" %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
  SyntaxHighlighter.all();
  </script>
</head>
<body>
  <!-- Navigation bar begin -->
  <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to('CoC Blog', root_path, :class => "navbar-brand") %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to('Home', root_path) %></li>
          <li><%= link_to('Blog', articles_path) %></li>
          <li><a href="#">Tutorials</a></li>
          <li><a href="#">Portfolio</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %></li>
          <% else %>
          <li><%= link_to('Sign In', new_user_session_path) %></li>
          <li><%= link_to('Register', new_user_registration_path) %></li>
          <% end %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->
  <!-- Navigation bar end -->
  <% if notice %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class=" alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p id="notice"><%= notice %></p>
      </div>
    </div>
  </div>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<% content_for :head do %>
<title>Consigliere - Editing <%= @static_page.title %></title>
<% end %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h1>Editing <%= @static_page.title %></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/static_pages/show.html.erb
<% content_for :head do %>
<title>Consigliere - <%= @static_page.title %></title>
<% end %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= @static_page.body.html_safe %>
    <div class="buttons">
      <% if can? :update, @static_page %>
      <%= link_to 'Edit', edit_static_page_path(@static_page), :class => "btn btn-primary" %>
      <% end %>
    </div>

  </div>
</div>